### ISSUE TITLE
errors in numba version

### ISSUE THREAD

**Issue by tmacattank** [Bharath2/iLQR#4]
Hi,
 **when i try to run the code, it comes out some errors as follows:** 
`Traceback (most recent call last):
  File "/home/ykezvd/workspace/iLQR/original/iLQR/examples/vehicle_control.py", line 70, in <module>
    xs, us, cost_trace = controller.fit(x0, us_init, 100)
  File "/home/ykezvd/workspace/iLQR/original/iLQR/examples/../ilqr/controller.py", line 34, in fit
    return run_ilqr(self.dynamics.f, self.dynamics.f_prime, self.cost.L,
  File "/home/ykezvd/anaconda3/lib/python3.9/site-packages/numba/core/dispatcher.py", line 482, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/ykezvd/anaconda3/lib/python3.9/site-packages/numba/core/dispatcher.py", line 423, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Failed in nopython mode pipeline (step: nopython frontend)
Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function array>) found for signature:
 
 >>> array(array(float64, 1d, C))
 
There are 4 candidate implementations:
  - Of which 4 did not match due to:
  Overload in function '_OverloadWrapper._build.<locals>.ol_generated': File: numba/core/overload_glue.py: Line 131.
    With argument(s): '(array(float64, 1d, C))':
   Rejected as the implementation raised a specific error:
     TypingError: Failed in nopython mode pipeline (step: nopython frontend)
   No implementation of function Function(<intrinsic stub>) found for signature:
    
    >>> stub(array(float64, 1d, C))
    
   There are 2 candidate implementations:
     - Of which 2 did not match due to:
     Intrinsic in function 'stub': File: numba/core/overload_glue.py: Line 35.
       With argument(s): '(array(float64, 1d, C))':
      Rejected as the implementation raised a specific error:
        TypingError: array(float64, 1d, C) not allowed in a homogeneous sequence
     raised from /home/ykezvd/anaconda3/lib/python3.9/site-packages/numba/core/typing/npydecl.py:487

`
**It seems that there are some conflicts in numba version, and my version only support a homogeneous sequence, can you give a list of your python and numba version?**

**Comment by housx** [comment]
遇到同样的问题

**Comment by ThomasMullen** [comment]
I have encountered the same problem too

**Comment by YBoWang** [comment]
Hi,

It seems that i had also encountered the same problem, and i fix it follows [Overload np.array to accept arrays](https://github.com/numba/numba/pull/4475). Specifically, i just change one line of code in ilqr/utils.py (line 103) from 
`  f_new = lambda *args: np.array(f(*args))` into `  f_new = lambda *args: np.asarray(f(*args))`.

If this problem remains, i think you could have a try.

Good luck.

**Comment by may210297** [comment]
> Hi,
> 
> It seems that i had also encountered the same problem, and i fix it follows [Overload np.array to accept arrays](https://github.com/numba/numba/pull/4475). Specifically, i just change one line of code in ilqr/utils.py (line 103) from ` f_new = lambda *args: np.array(f(*args))` into ` f_new = lambda *args: np.asarray(f(*args))`.
> 
> If this problem remains, i think you could have a try.
> 
> Good luck.

Thank you!
